###
POST http://localhost:3000/auth/register
Content-Type: application/json

{

  "fullname": "Petraitis",
  "email": "Jonas@email.com",
  "password": "slap123"
  
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{

  "fullname": "Petraitis",
  "email": "Jonas@email.com",
  "password": "slap123"
  
}