###
POST http://localhost:3000/auth/register
Content-Type: application/json

{

  "fullname": "Antanaitis",
  "email": "Antanas@email.com",
  "password": "slap124"
  
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{

  "fullname": "Antanaitis",
  "email": "Antanas@email.com",
  "password": "slap124"
  
}